export const FETCH_BOOKS_REQUESTED = "FETCH_BOOKS_REQUESTED";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";

export const ADD_BOOKS_REQUESTED = "ADD_BOOKS_REQUESTED";
export const ADD_BOOKS_SUCCESS = "ADD_BOOKS_SUCCESS";
export const ADD_BOOKS_FAILURE = "ADD_BOOKS_FAILURE";

export const UPDATE_BOOKS_REQUESTED = "UPDATE_BOOKS_REQUESTED";
export const UPDATE_BOOKS_SUCCESS = "UPDATE_BOOKS_SUCCESS";
export const UPDATE_BOOKS_FAILURE = "UPDATE_BOOKS_FAILURE";