export const FETCH_BOOKS = 'FETCH_BOOKS';

export const ADD_BOOKS = 'ADD_BOOKS';

export const UPDATE_BOOKS = 'UPDATE_BOOKS';
export const UPDATE_BOOK_PROGRESS = 'UPDATE_BOOK_PROGRESS';
export const UPDATE_BOOK_CATEGORY = 'UPDATE_BOOK_CATEGORY';
